import {
  defineConfig,
  presetUno,
  presetAttributify,
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
  ],
  theme: {
    colors: {
      warm: {
        50: '#FFFBF5',
        100: '#FFF8F0',
        200: '#FFE8D6',
        300: '#FFD4B8',
        400: '#FFB88C',
        500: '#FF9B7B',
        600: '#F07B5A',
        700: '#D95F40',
      },
      mint: {
        100: '#E0F2E9',
        200: '#C2E5D3',
        300: '#A8D8B9',
        400: '#7CC49A',
        500: '#5AB37E',
      },
      lavender: {
        100: '#EEE7F7',
        200: '#DDD0EF',
        300: '#D4C1EC',
        400: '#B89DE0',
        500: '#9C7DD4',
      },
      butter: {
        100: '#FFF6D6',
        200: '#FFEDAD',
        300: '#FFEAA7',
        400: '#FFDA6B',
        500: '#FFCB42',
      },
    },
    fontFamily: {
      round: ['"Nunito"', '"Quicksand"', 'system-ui', 'sans-serif'],
    },
    borderRadius: {
      'xl': '16px',
      '2xl': '24px',
      '3xl': '32px',
    },
    boxShadow: {
      soft: '0 4px 20px rgba(0, 0, 0, 0.06)',
      softer: '0 2px 12px rgba(0, 0, 0, 0.04)',
      pop: '0 6px 24px rgba(255, 155, 123, 0.25)',
    },
  },
  shortcuts: {
    'card': 'bg-white rounded-2xl shadow-soft p-4',
    'btn': 'px-5 py-2.5 rounded-xl font-medium transition-all duration-200 active:scale-95',
    'btn-primary': 'btn bg-warm-500 text-white hover:bg-warm-600 shadow-pop',
    'btn-secondary': 'btn bg-warm-100 text-warm-600 hover:bg-warm-200',
    'btn-ghost': 'btn bg-transparent text-gray-600 hover:bg-gray-100',
  },
  safelist: [
    'i-lucide-wallet',
    'i-lucide-star',
    'i-lucide-paintbrush',
    'i-lucide-plus',
    'i-lucide-minus',
    'i-lucide-chevron-right',
    'i-lucide-download',
    'i-lucide-upload',
    'i-lucide-settings',
    'i-lucide-home',
    'i-lucide-trash',
    'i-lucide-check',
    'i-lucide-x',
    'i-lucide-gift',
    'i-lucide-plane',
    'i-lucide-gem',
    'i-lucide-heart',
    'i-lucide-coffee',
    'i-lucide-shopping-cart',
    'i-lucide-utensils',
    'i-lucide-briefcase',
    'i-lucide-piggy-bank',
    'i-lucide-salad',
    'i-lucide-gamepad-2',
    'i-lucide-bus',
    'i-lucide-home as icon-home',
  ],
})
